### ISSUE TITLE
make errors relating to aasvg, binread, and kramdown-rfc

### ISSUE THREAD

**Issue by nealmcb** [ietf-wg-scitt/draft-ietf-scitt-architecture#6]
When I run `make` to build the document as instructed, I get lots of new tools installed (in a local `lib/.venv/` directory), culminating in this output:
```
[...]
Installing collected packages: webencodings, wcwidth, sortedcontainers, iddiff, charset-normalizer, appdirs, urllib3, toml, six, rfc-tidy, pyyaml, pycountry, markupsafe, lxml, intervaltree, idna, configargparse, certifi, requests, python-dateutil, pyang, jinja2, html5lib, google-i18n-address, archive-repo, xml2rfc, svgcheck
Successfully installed appdirs-1.4.4 archive-repo-0.0.2 certifi-2022.12.7 charset-normalizer-3.0.1 configargparse-1.5.3 google-i18n-address-2.5.2 html5lib-1.1 iddiff-0.4.3 idna-3.4 intervaltree-3.1.0 jinja2-3.1.2 lxml-4.9.2 markupsafe-2.1.2 pyang-2.5.3 pycountry-22.3.5 python-dateutil-2.8.2 pyyaml-6.0 requests-2.28.2 rfc-tidy-0.1.1 six-1.16.0 sortedcontainers-2.4.0 svgcheck-0.7.1 toml-0.10.2 urllib3-1.26.14 wcwidth-0.2.6 webencodings-0.5.1 xml2rfc-3.16.0
touch /srv/s/ietf/draft-ietf-scitt-architecture/lib/.venv/bin/.initialized-with-Makefile.venv
cat draft-ietf-scitt-architecture.md  | kramdown-rfc --v3 | lib/trace.sh draft-ietf-scitt-architecture.xml -s venue /srv/s/ietf/draft-ietf-scitt-architecture/lib/.venv/bin/python lib/add-note.py | lib/trace.sh draft-ietf-scitt-architecture.xml -s v2v3 /srv/s/ietf/draft-ietf-scitt-architecture/lib/.venv/bin/xml2rfc -q -s 'Setting consensus="true" for IETF STD document' --rfc-base-url https://www.rfc-editor.org/rfc/ --id-base-url https://datatracker.ietf.org/doc/html/ --cache=/home/neal/.cache/xml2rfc --v2v3 /dev/stdin -o /dev/stdout >draft-ietf-scitt-architecture.xml
lib/trace.sh: line 14: exec: kramdown-rfc: not found
Error: Unable to parse the XML document: /dev/stdin
make: *** [lib/main.mk:72: draft-ietf-scitt-architecture.xml] Error 1
make: *** Deleting file 'draft-ietf-scitt-architecture.xml'
```

So I looked at the setup doc: [i\-d\-template/SETUP\.md at main · martinthomson/i\-d\-template · GitHub](https://github.com/martinthomson/i-d-template/blob/main/doc/SETUP.md)

It wasn't quite clear how to install bundler, but this seems to have worked on Ubuntu 20.04:

`sudo apt install ruby-bundler`

After running `make` again, I got an error with these interesting lines:

```
/srv/s/ietf/draft-ietf-scitt-architecture/lib/.gems/ruby/2.7.0/gems/kramdown-rfc2629-1.6.23/lib/kramdown-rfc2629.rb:463:in `binread': No such file or directory @ rb_sysopen - /home/neal/.cache/xml2rfc/kdrfc-1_6_23-svg_tool_process-f6af3c66d015d02c71df638c578665ec07ac4bde.cache (Errno::ENOENT)
...
/usr/lib/ruby/2.7.0/open3.rb:213:in `spawn': No such file or directory - aasvg (Errno::ENOENT)
```

Any hints on what else is needed?

**Comment by SteveLasker** [comment]
@nealmcb, this looks to be fixed with several edits. Please re-open if you find new issues.
